version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
      - POSTGRES_HOST=yourdbhost
      - POSTGRES_PORT=5432
